### ISSUE TITLE
Create User - fields missaligned

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#4]
![image](https://cloud.githubusercontent.com/assets/7820679/9152109/c3ad0e5e-3de9-11e5-87a9-350839a3f156.png)

**Comment by Pierroutt** [comment]
It looks aligned on my computer right now, this might have occured due to the error in the main users screen or it might just be an issue with the css not working specifically for safari (or whichever browser you are using). Either way I hope the error was temporary,otherwise I have no idea how I can get rid of this because it is aligned on my screen

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#4
